
enum EModalContent{
    NONE = "NONE" , 
    LOGIN = "LOGIN", 
    LOGIN_SUCCESS = "LOGIN_SUCCESS",
    REGISTRATION = "REGISTRATION" , 
    REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS" , 
    RECOVER_PASSWORD = "RECOVER_PASSWORD", 
}

export default EModalContent